"""change version to string for timestamps and added is_active for offline evaluation if needed

Revision ID: 9b42ab20c450
Revises: 884ec015dfc2
Create Date: 2025-12-31 16:24:43.475066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid
# revision identifiers, used by Alembic.
revision: str = '9b42ab20c450'
down_revision: Union[str, Sequence[str], None] = '884ec015dfc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), default=uuid.uuid4, server_default=sa.text("gen_random_uuid()"), nullable=False),
    sa.Column('model_version_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('prediction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.version'], name=op.f('predictions_model_version_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('predictions_pkey'))
    )
    op.add_column('model_versions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('idx_model_version_id'), 'predictions', ['model_version_id'], unique=False)
    op.create_index(op.f('idx_customer_id'), 'predictions', ['customer_id'], unique=False)
    op.create_index(op.f('idx_created_at'), 'predictions', ['created_at'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_created_at'), table_name='predictions')
    op.drop_index(op.f('idx_customer_id'), table_name='predictions')
    op.drop_index(op.f('idx_model_version_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    # ### end Alembic commands ###
